### ISSUE TITLE
please enable to use "=" in cell

### ISSUE THREAD

**Issue by ykamez** [qsona/doctordata#2]
When I use "=" in the first line's cell, it separates like the example below.
セルの1行目に"="が入っていると、そこでkeyとvalueに分かれてしまうのを修正してお願いしたいです。

ex：
(excel)
```
10
#当日=0としたときxxx
```
(convert to json)
```      
"10\n#当日": "0としたときxxx",
```

**Comment by qsona** [comment]
I think I can fix by encoding url, but it becomes slower.
I want to throw the dependency to Faraday away, because now it is really doing useless execution, i mean, first join by '=' and re-parse it.
Could you please work for this issue?

**Comment by ykamez** [comment]
hi, @qsona. I fixed bug. please review.
https://github.com/qsona/doctordata/pull/3
